# ------------------------------------------------------------------
# General settings
# ------------------------------------------------------------------
general:
  base_output_dir: "outputs/eda"          # top-level folder for stats, logs
  plots_output_dir: "outputs/eda/plots"   # where to save plots

# ------------------------------------------------------------------
# Data loader options
# ------------------------------------------------------------------
data_loader:
  input_dir: "data/raw"
  filename: "MachineLearningRating_v3.txt"
  delimiter: "|"                 
  file_type: "txt"               # "txt" or "csv"

# ------------------------------------------------------------------
# Data cleaner options
# ------------------------------------------------------------------
data_cleaner:
  output_path: "data/processed/insurance_cleaned_data.csv"

# ------------------------------------------------------------------
# Visualization settings
# ------------------------------------------------------------------
visualisations:
  histograms:    ["TotalPremium", "TotalClaims"]
  bar_charts:    ["VehicleType", "Gender"]
  box_plots:     ["TotalPremium"]
  geo_column:    "Province"
  insight_plots:
    - kind: "bar"
      name: "avg_premium_by_province"
      x: "Province"
      y: "TotalPremium"
      agg: "mean"
    - kind: "scatter"
      name: "claims_vs_premium_by_vehicle"
      x: "TotalPremium"
      y: "TotalClaims"
      hue: "VehicleType"
    - kind: "box"
      name: "loss_ratio_by_gender"
      x: "Gender"
      y: "LossRatio"
