alpha: 0.05

data:
  cleaned_path: "data/processed/insurance_cleaned_data.csv"

tests:
  - name: "Province LossRatio Difference"
    feature: "Province"
    group_a: "Western Cape"
    group_b: "Gauteng"
    kpi: "loss_ratio"
    test: "ttest"
    covariates: ["VehicleType", "CoverType"]

  - name: "Gender LossRatio Difference"
    feature: "Gender"
    group_a: "Male"
    group_b: "Female"
    kpi: "loss_ratio"
    test: "mw_u"

  - name: "ZIP Margin Difference"
    feature: "PostalCode"
    group_a: "1459"
    group_b: "8000"
    kpi: "loss_ratio"
    test: "ttest"
