alpha: 0.05           # significance threshold

data:
  cleaned_path: "data/processed/insurance_cleaned_data.csv"

tests:
  # 1 Province difference (margin)
  - name: "Province Margin"
    feature: "Province"
    group_a: "Gauteng"
    group_b: "Western Cape"
    kpi: "margin"
    test: "ttest"

  # 2 Gender margin
  - name: "Gender Margin"
    feature: "Gender"
    group_a: "Male"
    group_b: "Female"
    kpi: "margin"
    test: "mw_u"

  # 3 PostalCode margin
  - name: "PostalCode Margin"
    feature: "PostalCode"
    group_a: "1459"
    group_b: "8000"
    kpi: "margin"
    test: "ttest"

reports:
  summary_md: "reports/task_3_hypothesis_summary.md"
