# ------------------------------------------------------------------
data:
  cleaned_path: "data/processed/insurance_cleaned_data.csv"

# ------------------------------------------------------------------
split:
  test_size: 0.2
  random_state: 42
  stratify: "ClaimOccurred"

# ------------------------------------------------------------------
classifier:
  model: "xgboost"          # options: xgboost | logistic | random_forest_cls
  params:
    n_estimators: 400
    max_depth: 6
    learning_rate: 0.05
    scale_pos_weight: 380

# ------------------------------------------------------------------
regressor:
  model: "xgboost_reg"      # options: xgboost_reg | linear_reg | random_forest
  params:
    n_estimators: 600
    max_depth: 6
    learning_rate: 0.05

# ------------------------------------------------------------------
severity:
  model: "xgboost_reg"
  params:
    n_estimators: 200
    max_depth: 4
    learning_rate: 0.1

# ------------------------------------------------------------------
output:
  model_dir: "models"
  reports_dir: "reports"
  shap_sample_size: 100
  enable_shap: true       # ✅ add this line to disable SHAP
# ------------------------------------------------------------------
